using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Linq;
using System.Threading.Tasks;
using System.Windows.Forms;
using DevExpress.XtraEditors;
using DevExpress.Data.PLinq;

namespace Inventario
{
    public partial class XtraFormMovspz : DevExpress.XtraEditors.XtraForm
    {
        Inventario.App_Code.Model.MovsPzQuery _dataContext;
        string _filtering = "";
        DevExpress.Data.PLinq.PLinqInstantFeedbackSource _nerePLinkiu;
        public XtraFormMovspz()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            this.pLinqInstantFeedbackSource1.GetEnumerable += pLinqInstantFeedbackSource1_GetEnumerable;
            // This line of code is generated by Data Source Configuration Wizard
            this.pLinqInstantFeedbackSource1.DismissEnumerable += pLinqInstantFeedbackSource1_DismissEnumerable;

            _nerePLinkiu = new DevExpress.Data.PLinq.PLinqInstantFeedbackSource();
            _nerePLinkiu.GetEnumerable += nerePLinkiu_GetEnumerable;
        }

        // This event is generated by Data Source Configuration Wizard
        void pLinqInstantFeedbackSource1_GetEnumerable(object sender, DevExpress.Data.PLinq.GetEnumerableEventArgs e)
        {

            // Instantiate a new DataContext
            //Inventario.App_Code.Model.MovsPzQuery dataContext = new Inventario.App_Code.Model.MovsPzQuery();
            _dataContext = new Inventario.App_Code.Model.MovsPzQuery();
            // Assign a queryable source to the PLinqInstantFeedbackSource
            e.Source = _dataContext.DBMovspz;
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissEnumerable event handler
            e.Tag = _dataContext;

        }

        // This event is generated by Data Source Configuration Wizard
        void pLinqInstantFeedbackSource1_DismissEnumerable(object sender, DevExpress.Data.PLinq.GetEnumerableEventArgs e)
        {

            // Dispose of the DataContext
            //((Inventario.App_Code.Model.MovsPzQuery)e.Tag).Dispose();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            // Instantiate a new DataContext
            //Inventario.App_Code.Model.MovsPzQuery dataContext = new Inventario.App_Code.Model.MovsPzQuery();
            //// Assign a queryable source to the PLinqInstantFeedbackSource
            //var result= dataContext.DBMovspz.Where(p => p.USUARIO == "Android");
            //gridControl1.DataSource = result;

            //// Assign the DataContext to the Tag property,
            //// to dispose of it in the DismissEnumerable event handler
            ////e.Tag = dataContext;

            //DevExpress.Data.PLinq.PLinqInstantFeedbackSource _nerePLinkiu = new DevExpress.Data.PLinq.PLinqInstantFeedbackSource();
            //linqInstantFeedbackSource1.KeyExpression = "PurchaseOrderID"; DevExpress.Data.v22.1.dll

            //_nerePLinkiu.GetEnumerable += nerePLinkiu_GetEnumerable;
            gridControl1.DataSource = null;
            _filtering = "iurgi";
            gridControl1.DataSource = _nerePLinkiu;
            //gridControl1.DataSource = pLinqInstantFeedbackSource1;

            //_dataContext.DBMovspz.Where(p => p.USUARIO == "Android");
            ////_dataContext.SaveChanges();
            ////pLinqInstantFeedbackSource1.Refresh();
            ////this.pLinqInstantFeedbackSource1.GetEnumerable;
            //gridControl1.DataSource = pLinqInstantFeedbackSource1;
            //pLinqInstantFeedbackSource1.Refresh();




        }

        private void nerePLinkiu_GetEnumerable(object sender, GetEnumerableEventArgs e)
        {

            DevExpress.Data.PLinq.PLinqInstantFeedbackSource bidaltzailea = (DevExpress.Data.PLinq.PLinqInstantFeedbackSource)sender;
            

            // Instantiate a new DataContext
            //Inventario.App_Code.Model.MovsPzQuery dataContext = new Inventario.App_Code.Model.MovsPzQuery();
            //_dataContext.DBMovspz.Where(p => p.USUARIO == "Android");
            // Assign a queryable source to the PLinqInstantFeedbackSource
            e.Source = _dataContext.DBMovspz.Where(p => p.USUARIO == _filtering);
            // Assign the DataContext to the Tag property,
            // to dispose of it in the DismissEnumerable event handler
            //e.Tag = _dataContext;
        }

        private void button2_Click(object sender, EventArgs e)
        {
            gridControl1.DataSource = null;
            _filtering = "Android";
            gridControl1.DataSource = _nerePLinkiu;
        }
    }
}